# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98802f15251fbb6d9ac7e61938931b2c1c4f7b8050be397302b0471c43984a1db4c010092f46b0875a37303f6567bcaa20c7dc8c18f2bc1e456c52c940bd2001

test:
  secret_key_base: c726a7977a3e5183de78e51c4577a64444439f7eddb0be70efd0ecad39f6a63c794dfe54277275997665d2c07918f32050aaaf9784a1926ba3be96ea708b4c7c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
